In [8]:
import numpy as np
import cv2
duration = 2
fps = 10
out = cv2.VideoWriter('test_video.avi', cv2.VideoWriter_fourcc(*'XVID'), fps, (10, 10), True)
for _ in range(int(fps * duration / 2)):
    data = np.zeros([10,10,3], dtype='uint8')
    out.write(data)
    
for _ in range(int(fps * duration / 2)):
    data = np.ones([10,10,3], dtype='uint8')
    data = data * 125
    
    print(data)
    out.write(data)
out.release()

[[[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]
  [125 125 125]]

 [[125 125 125]
  [125 125 1